# -*- coding: utf-8 -*-
"""ECE1508_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yK-RBNXdwuxLA5L4gRbkTHGepHe0LjNo

# Learning the Data Distribution of Handwritten Digits using a Variational Autoencoder

A simple VAE on MNIST and Fashion-MNIST. The experiments analyze Gaussian latent distributions, latent-space dimensionality, reconstruction quality, and random sample generation.
"""

# Setup

import random
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Device:", device)

# Datasets: Load MNIST and Fashion-MNIST

transform = transforms.ToTensor()
batch_size = 128

# MNIST
train_dataset = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root="./data", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Fashion-MNIST
fashion_train_dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform)
fashion_test_dataset = datasets.FashionMNIST(root="./data", train=False, download=True, transform=transform)

fashion_train_loader = DataLoader(fashion_train_dataset, batch_size=batch_size, shuffle=True)
fashion_test_loader = DataLoader(fashion_test_dataset, batch_size=batch_size,shuffle=False)

# VAE Model: Define functions

input_dim = 784
hidden_dim = 256

class VAE(nn.Module):
    def __init__(self, input_dim=784, hidden_dim=256, latent_dim=8):
        super().__init__()

        self.encoder = nn.Sequential(nn.Linear(input_dim, hidden_dim), nn.ReLU())
        self.fc_mu = nn.Linear(hidden_dim, latent_dim)
        self.fc_logvar = nn.Linear(hidden_dim, latent_dim)
        self.decoder = nn.Sequential(nn.Linear(latent_dim, hidden_dim), nn.ReLU(), nn.Linear(hidden_dim, input_dim), nn.Sigmoid())

    def encode(self, x):
        hidden = self.encoder(x)
        mu = self.fc_mu(hidden)
        logvar = self.fc_logvar(hidden)
        return mu, logvar

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5*logvar)
        epsilon = torch.randn_like(std)
        return mu+epsilon*std

    def decode(self, z):
        return self.decoder(z)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        reconstructed = self.decode(z)
        return reconstructed, mu, logvar

def vae_loss(reconstructed, original, mu, logvar):
    recon_loss = F.binary_cross_entropy(reconstructed, original, reduction="sum")
    kl_loss = -0.5*torch.sum(1+logvar-mu.pow(2)-logvar.exp())
    total_loss = recon_loss+kl_loss

    return total_loss, recon_loss, kl_loss


def train_model(model, loader, optimizer, num_epochs, device):
    history = {"total": [], "recon": [], "kl": []}

    for epoch in range(num_epochs):
        model.train()

        total_sum = 0
        recon_sum = 0
        kl_sum = 0

        for images, _ in loader:
            images = images.to(device)
            images = images.view(images.size(0), -1)

            optimizer.zero_grad()

            reconstructed, mu, logvar = model(images)

            total_loss, recon_loss, kl_loss = vae_loss(reconstructed, images, mu, logvar)

            total_loss.backward()
            optimizer.step()

            total_sum += total_loss.item()
            recon_sum += recon_loss.item()
            kl_sum += kl_loss.item()

        dataset_size = len(loader.dataset)

        history["total"].append(total_sum/dataset_size)
        history["recon"].append(recon_sum/dataset_size)
        history["kl"].append(kl_sum/dataset_size)

    return model, history

def evaluate_model(model, loader, device):

    model.eval()

    total_sum = 0
    recon_sum = 0
    kl_sum = 0

    with torch.no_grad():
        for images, _ in loader:

            images = images.to(device)
            images = images.view(images.size(0), -1)

            reconstructed, mu, logvar = model(images)

            total_loss, recon_loss, kl_loss = vae_loss(reconstructed, images, mu, logvar)

            total_sum += total_loss.item()
            recon_sum += recon_loss.item()
            kl_sum += kl_loss.item()

    dataset_size = len(loader.dataset)

    return {"total_loss": total_sum/dataset_size, "recon_loss": recon_sum/dataset_size,"kl_loss": kl_sum/dataset_size}

# MNIST Training: Train with latent dimensions 2, 8, and 16 & Evaluation

latent_dims = [2, 8, 16]
num_epochs = 10

mnist_models = {}
mnist_results = {}
mnist_histories = {}

for dim in latent_dims:

    print(f"Training MNIST VAE with latent_dim = {dim}")

    current_model = VAE(input_dim=input_dim, hidden_dim=hidden_dim, latent_dim=dim).to(device)

    optimizer = torch.optim.Adam(current_model.parameters(), lr=1e-3)

    current_model, history = train_model(current_model, train_loader, optimizer, num_epochs, device)

    mnist_models[dim] = current_model
    mnist_histories[dim] = history
    mnist_results[dim] = evaluate_model(current_model, test_loader, device)

    print(mnist_results[dim])

# MNIST Results

plt.plot(mnist_histories[8]["total"], label="Total")
plt.plot(mnist_histories[8]["recon"], label="Reconstruction")
plt.plot(mnist_histories[8]["kl"], label="KL")

plt.xlabel("Epoch")
plt.ylabel("Average Loss")
plt.title("Training Loss (Dim = 8)")
plt.legend()
plt.show()


# Test loss comparison
recon_losses = [mnist_results[d]["recon_loss"] for d in latent_dims]
kl_losses = [mnist_results[d]["kl_loss"] for d in latent_dims]
total_losses = [mnist_results[d]["total_loss"] for d in latent_dims]

plt.plot(latent_dims, total_losses, marker="o", label="Total")
plt.plot(latent_dims, recon_losses, marker="o", label="Reconstruction")
plt.plot(latent_dims, kl_losses, marker="o", label="KL")

plt.xlabel("Latent Dimension")
plt.ylabel("Test Loss")
plt.title("Latent Dimension Comparison")
plt.legend()
plt.show()

for dim in latent_dims:
    print(
        f"Dim {dim} | "
        f"Total: {mnist_results[dim]['total_loss']:.4f} | "
        f"Recon: {mnist_results[dim]['recon_loss']:.4f} | "
        f"KL: {mnist_results[dim]['kl_loss']:.4f}"
    )

## Gaussian Distribution and compare the dim=8 latent distribution

model_8 = mnist_models[8]
model_8.eval()

all_z = []

with torch.no_grad():
    for images, _ in test_loader:
        images = images.to(device).view(images.size(0), -1)

        mu, logvar = model_8.encode(images)
        z = model_8.reparameterize(mu, logvar)
        all_z.append(z.cpu())

all_z = torch.cat(all_z)

x = np.linspace(-4, 4, 200)
gaussian = (1/np.sqrt(2*np.pi))*np.exp(-0.5*x**2)

plt.hist(all_z.flatten().numpy(), bins=90, density=True, label="Learned Latent Distribution")
plt.plot(x, gaussian, label="N(0,1)")

plt.xlabel("z")
plt.ylabel("Density")
plt.title("Latent Distribution for Dim = 8")
plt.legend()
plt.show()

# Mean and standard deviation of each latent dimension
for i in range(8):
    print(
        f"Dim {i + 1}: "
        f"mean={all_z[:, i].mean():.3f}, "
        f"std={all_z[:, i].std():.3f}"
    )

# 2D Latent Space Analysis

model_2 = mnist_models[2]
model_2.eval()

all_mu = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device).view(images.size(0), -1)

        mu, _ = model_2.encode(images)

        all_mu.append(mu.cpu())
        all_labels.append(labels)

all_mu = torch.cat(all_mu)
all_labels = torch.cat(all_labels)

plt.figure(figsize=(7, 5))

scatter = plt.scatter(all_mu[:, 0], all_mu[:, 1], c=all_labels, cmap="tab10", s=5)

plt.colorbar(scatter, ticks=range(10))
plt.xlabel("Latent Dimension 1")
plt.ylabel("Latent Dimension 2")
plt.title("2D Latent Space of MNIST")
plt.show()

# Generate images across different positions in the 2D latent space.

grid_size = 15

grid_x = torch.linspace(-3, 3, grid_size)
grid_y = torch.linspace(3, -3, grid_size)

canvas = np.zeros((28 * grid_size, 28 * grid_size))

with torch.no_grad():
    for i, y in enumerate(grid_y):
        for j, x in enumerate(grid_x):

            z = torch.tensor([[x, y]], dtype=torch.float32, device=device)
            image = model_2.decode(z)
            image = image.view(28, 28).cpu().numpy()
            canvas[i*28:(i+1)*28, j*28:(j+1)*28] = image

plt.imshow(canvas)
plt.xticks([])
plt.yticks([])
plt.xlabel("Latent Dimension 1")
plt.ylabel("Latent Dimension 2")
plt.title("Generated Images Across the 2D Latent Space")
plt.show()

# MNIST Visual Comparison

num_images = 10

test_images, _ = next(iter(test_loader))
test_images = test_images[:num_images].to(device)
flat_images = test_images.view(num_images, -1)

original_strip = torch.cat([test_images[i].cpu() for i in range(num_images)], dim=2)

plt.imshow(original_strip.squeeze())
plt.title("Original Images")
plt.axis("off")
plt.show()


# Reconstruction comparison
for dim in latent_dims:
    model = mnist_models[dim]
    model.eval()

    with torch.no_grad():
        mu, _ = model.encode(flat_images)
        reconstructed = model.decode(mu)
        reconstructed = reconstructed.view(-1, 1, 28, 28)

    recon_strip = torch.cat([reconstructed[i].cpu() for i in range(num_images)], dim=2)

    plt.imshow(recon_strip.squeeze())
    plt.title(f"Reconstructed Images, Latent Dim {dim}")
    plt.axis("off")
    plt.show()


# Generated sample comparison
for dim in latent_dims:
    model = mnist_models[dim]
    model.eval()

    with torch.no_grad():
        z = torch.randn(num_images, dim, device=device)
        generated = model.decode(z)
        generated = generated.view(-1, 1, 28, 28)

    generated_strip = torch.cat([generated[i].cpu() for i in range(num_images)], dim=2)

    plt.imshow(generated_strip.squeeze())
    plt.title(f"Generated Images - Latent Dim {dim}")
    plt.axis("off")
    plt.show()

# Fashion-MNIST Training with latent dimensions 2, 8, and 16 & Evaluation

fashion_models = {}
fashion_results = {}
fashion_histories = {}

for dim in latent_dims:

    print(f"Training Fashion-MNIST VAE with latent_dim = {dim}")

    current_model = VAE(input_dim=input_dim, hidden_dim=hidden_dim, latent_dim=dim).to(device)

    optimizer = torch.optim.Adam( current_model.parameters(), lr=1e-3)

    current_model, history = train_model(current_model, fashion_train_loader, optimizer, num_epochs, device)

    fashion_models[dim] = current_model
    fashion_histories[dim] = history
    fashion_results[dim] = evaluate_model( current_model, fashion_test_loader, device)

    print(fashion_results[dim])

# 9. Fashion-MNIST: Compare reconstruction, KL, and total test losses

fashion_recon_losses = [fashion_results[d]["recon_loss"] for d in latent_dims]
fashion_kl_losses = [fashion_results[d]["kl_loss"] for d in latent_dims]
fashion_total_losses = [fashion_results[d]["total_loss"] for d in latent_dims]

plt.plot(latent_dims, fashion_total_losses, marker="o", label="Total")
plt.plot(latent_dims, fashion_recon_losses, marker="o", label="Reconstruction")
plt.plot(latent_dims, fashion_kl_losses, marker="o", label="KL")

plt.xlabel("Latent Dimension")
plt.ylabel("Test Loss")
plt.title("Fashion-MNIST Latent Dimension Comparison")
plt.legend()
plt.show()

for dim in latent_dims:
    print(
        f"Dim {dim} | "
        f"Total: {fashion_results[dim]['total_loss']:.4f} | "
        f"Recon: {fashion_results[dim]['recon_loss']:.4f} | "
        f"KL: {fashion_results[dim]['kl_loss']:.4f}"
    )

# Fashion-MNIST Visual Comparison

num_images = 10

fashion_images, _ = next(iter(fashion_test_loader))
fashion_images = fashion_images[:num_images].to(device)
flat_fashion = fashion_images.view(num_images, -1)

original_strip = torch.cat([fashion_images[i].cpu() for i in range(num_images)], dim=2)

plt.imshow(original_strip.squeeze(),cmap="gray")
plt.title("Original Fashion-MNIST Images")
plt.show()


for dim in latent_dims:

    model = fashion_models[dim]
    model.eval()
    with torch.no_grad():
        mu, _ = model.encode(flat_fashion)
        reconstructed = model.decode(mu)
        reconstructed = reconstructed.view(-1, 1, 28, 28)

    recon_strip = torch.cat([reconstructed[i].cpu() for i in range(num_images)], dim=2)

    plt.imshow(recon_strip.squeeze(), cmap="gray")
    plt.title(f"Reconstructed Fashion-MNIST, Latent Dim {dim}")
    plt.show()

for dim in latent_dims:

    model = fashion_models[dim]
    model.eval()

    with torch.no_grad():
        z = torch.randn(num_images, dim, device=device)
        generated = model.decode(z)
        generated = generated.view(-1, 1, 28, 28)

    generated_strip = torch.cat([generated[i].cpu() for i in range(num_images)], dim=2)

    plt.imshow(generated_strip.squeeze(), cmap="gray")
    plt.title(f"Generated Fashion-MNIST, Latent Dim {dim}")
    plt.show()